import boto3

dynamodb=boto3.client("dynamodb")
dynamoTable=dynamodb.Table("greyhawk_calendar_data")
dynamoTable.put_item(
  {
    "RecordNumber": 1,
    "MonthNumber": 1,
    "Month": "Needfest",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "This frigid seven-day period marks the transition from one calendar year to another, and is usually accounted as the start of the new year.",
    "Luna": "New Moon",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 2,
    "MonthNumber": 1,
    "Month": "Needfest",
    "Day": 2,
    "DayOfWeek": "Sunday",
    "Season": "This frigid seven-day period marks the transition from one calendar year to another, and is usually accounted as the start of the new year.",
    "Luna": "New Moon",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 3,
    "MonthNumber": 1,
    "Month": "Needfest",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "This frigid seven-day period marks the transition from one calendar year to another, and is usually accounted as the start of the new year.",
    "Luna": "New Moon Fading",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 4,
    "MonthNumber": 1,
    "Month": "Needfest",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "This frigid seven-day period marks the transition from one calendar year to another, and is usually accounted as the start of the new year.",
    "Luna": "New Moon Fading",
    "Celene": "Full Moon Fading",
    "Solstace": "The Winter Solstice is the shortest day of the year.",
    "Special": ""
  },
  {
    "RecordNumber": 5,
    "MonthNumber": 1,
    "Month": "Needfest",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "This frigid seven-day period marks the transition from one calendar year to another, and is usually accounted as the start of the new year.",
    "Luna": "Waxing Crescent",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 6,
    "MonthNumber": 1,
    "Month": "Needfest",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "This frigid seven-day period marks the transition from one calendar year to another, and is usually accounted as the start of the new year.",
    "Luna": "Waxing Crescent",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 7,
    "MonthNumber": 1,
    "Month": "Needfest",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "This frigid seven-day period marks the transition from one calendar year to another, and is usually accounted as the start of the new year.",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 8,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Winter",
    "Luna": "First Quarter",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 9,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 2,
    "DayOfWeek": "Monday",
    "Season": "Winter",
    "Luna": "First Quarter",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 10,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Winter",
    "Luna": "First Quarter Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 11,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Winter",
    "Luna": "First Quarter Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 12,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Winter",
    "Luna": "Waxing Gibbous",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 13,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Winter",
    "Luna": "Waxing Gibbous",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 14,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Winter",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 15,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Winter",
    "Luna": "Full Moon",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 16,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 9,
    "DayOfWeek": "Tuesday",
    "Season": "Winter",
    "Luna": "Full Moon",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 17,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Winter",
    "Luna": "Full Moon Fading",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 18,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Winter",
    "Luna": "Full Moon Fading",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 19,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Winter",
    "Luna": "Waning Gibbous",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 20,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Winter",
    "Luna": "Waning Gibbous",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 21,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Winter",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 22,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Winter",
    "Luna": "Last Quarter",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 23,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 16,
    "DayOfWeek": "Wednesday",
    "Season": "Winter",
    "Luna": "Last Quarter",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 24,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Winter",
    "Luna": "Last Quarter Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 25,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Winter",
    "Luna": "Last Quarter Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 26,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Winter",
    "Luna": "Waning Crescent",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 27,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Winter",
    "Luna": "Waning Crescent",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 28,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Winter",
    "Luna": "Waning Crescent Fading",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 29,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Winter",
    "Luna": "New Moon",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 30,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 23,
    "DayOfWeek": "Thursday",
    "Season": "Winter",
    "Luna": "New Moon",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 31,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Winter",
    "Luna": "New Moon Fading",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 32,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Winter",
    "Luna": "New Moon Fading",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 33,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Winter",
    "Luna": "Waxing Crescent",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 34,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Winter",
    "Luna": "Waxing Crescent",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 35,
    "MonthNumber": 2,
    "Month": "Fireseek",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Winter",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 36,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Spring",
    "Luna": "First Quarter",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 37,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 2,
    "DayOfWeek": "Monday",
    "Season": "Spring",
    "Luna": "First Quarter",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 38,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Spring",
    "Luna": "First Quarter Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 39,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Spring",
    "Luna": "First Quarter Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 40,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Spring",
    "Luna": "Waxing Gibbous",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 41,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Spring",
    "Luna": "Waxing Gibbous",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 42,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Spring",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 43,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Spring",
    "Luna": "Full Moon",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 44,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 9,
    "DayOfWeek": "Tuesday",
    "Season": "Spring",
    "Luna": "Full Moon",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 45,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Spring",
    "Luna": "Full Moon Fading",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 46,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Spring",
    "Luna": "Full Moon Fading",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 47,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Spring",
    "Luna": "Waning Gibbous",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 48,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Spring",
    "Luna": "Waning Gibbous",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 49,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Spring",
    "Luna": "Waning Gibbous Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 50,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Spring",
    "Luna": "Last Quarter",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 51,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 16,
    "DayOfWeek": "Wednesday",
    "Season": "Spring",
    "Luna": "Last Quarter",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 52,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Spring",
    "Luna": "Last Quarter Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 53,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Spring",
    "Luna": "Last Quarter Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 54,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Spring",
    "Luna": "Waning Crescent",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 55,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Spring",
    "Luna": "Waning Crescent",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 56,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Spring",
    "Luna": "Waning Crescent Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 57,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Spring",
    "Luna": "New Moon",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 58,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 23,
    "DayOfWeek": "Thursday",
    "Season": "Spring",
    "Luna": "New Moon",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 59,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Spring",
    "Luna": "New Moon Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 60,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Spring",
    "Luna": "New Moon Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 61,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Spring",
    "Luna": "Waxing Crescent",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 62,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Spring",
    "Luna": "Waxing Crescent",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 63,
    "MonthNumber": 3,
    "Month": "Readying",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Spring",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 64,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Spring",
    "Luna": "First Quarter",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 65,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 2,
    "DayOfWeek": "Monday",
    "Season": "Spring",
    "Luna": "First Quarter",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 66,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Spring",
    "Luna": "First Quarter Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 67,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Spring",
    "Luna": "First Quarter Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 68,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Spring",
    "Luna": "Waxing Gibbous",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 69,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Spring",
    "Luna": "Waxing Gibbous",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 70,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Spring",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 71,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Spring",
    "Luna": "Full Moon",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 72,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 9,
    "DayOfWeek": "Tuesday",
    "Season": "Spring",
    "Luna": "Full Moon",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 73,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Spring",
    "Luna": "Full Moon Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 74,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Spring",
    "Luna": "Full Moon Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 75,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Spring",
    "Luna": "Waning Gibbous",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 76,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Spring",
    "Luna": "Waning Gibbous",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 77,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Spring",
    "Luna": "Waning Gibbous Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 78,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Spring",
    "Luna": "Last Quarter",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 79,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 16,
    "DayOfWeek": "Wednesday",
    "Season": "Spring",
    "Luna": "Last Quarter",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 80,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Spring",
    "Luna": "Last Quarter Fading",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 81,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Spring",
    "Luna": "Last Quarter Fading",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 82,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Spring",
    "Luna": "Waning Crescent",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 83,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Spring",
    "Luna": "Waning Crescent",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 84,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Spring",
    "Luna": "Waning Crescent Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 85,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Spring",
    "Luna": "New Moon",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 86,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 23,
    "DayOfWeek": "Thursday",
    "Season": "Spring",
    "Luna": "New Moon",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 87,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Spring",
    "Luna": "New Moon Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 88,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Spring",
    "Luna": "New Moon Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 89,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Spring",
    "Luna": "Waxing Crescent",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 90,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Spring",
    "Luna": "Waxing Crescent",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 91,
    "MonthNumber": 4,
    "Month": "Coldeven",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Spring",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 92,
    "MonthNumber": 5,
    "Month": "Growfest",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "This seven-day period marks the transition from spring to summer.",
    "Luna": "First Quarter",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 93,
    "MonthNumber": 5,
    "Month": "Growfest",
    "Day": 2,
    "DayOfWeek": "Thursday",
    "Season": "This seven-day period marks the transition from spring to summer.",
    "Luna": "First Quarter",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 94,
    "MonthNumber": 5,
    "Month": "Growfest",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "This seven-day period marks the transition from spring to summer.",
    "Luna": "First Quarter Fading",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 95,
    "MonthNumber": 5,
    "Month": "Growfest",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "This seven-day period marks the transition from spring to summer.",
    "Luna": "First Quarter Fading",
    "Celene": "Full Moon Fading",
    "Solstace": "The Spring Equinox, also known as the Vernal Equinox, is when the night and day are approximately equal in length, marking the beginning of Spring and the approach of Summer.",
    "Special": ""
  },
  {
    "RecordNumber": 96,
    "MonthNumber": 5,
    "Month": "Growfest",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "This seven-day period marks the transition from spring to summer.",
    "Luna": "Waxing Gibbous",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 97,
    "MonthNumber": 5,
    "Month": "Growfest",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "This seven-day period marks the transition from spring to summer.",
    "Luna": "Waxing Gibbous",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 98,
    "MonthNumber": 5,
    "Month": "Growfest",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "This seven-day period marks the transition from spring to summer.",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 99,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "Full Moon",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 100,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 2,
    "DayOfWeek": "Monday",
    "Season": "Low Summer",
    "Luna": "Full Moon",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 101,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 102,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 103,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 104,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 105,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 106,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "Last Quarter",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 107,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 9,
    "DayOfWeek": "Tuesday",
    "Season": "Low Summer",
    "Luna": "Last Quarter",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 108,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 109,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 110,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 111,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 112,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 113,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "New Moon",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 114,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 16,
    "DayOfWeek": "Wednesday",
    "Season": "Low Summer",
    "Luna": "New Moon",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 115,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "New Moon Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 116,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "New Moon Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 117,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 118,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 119,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 120,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "First Quarter",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 121,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 23,
    "DayOfWeek": "Thursday",
    "Season": "Low Summer",
    "Luna": "First Quarter",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 122,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 123,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 124,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 125,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 126,
    "MonthNumber": 6,
    "Month": "Planting",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 127,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "Full Moon",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 128,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 2,
    "DayOfWeek": "Monday",
    "Season": "Low Summer",
    "Luna": "Full Moon",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 129,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 130,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 131,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 132,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 133,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 134,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "Last Quarter",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 135,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 9,
    "DayOfWeek": "Tuesday",
    "Season": "Low Summer",
    "Luna": "Last Quarter",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 136,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 137,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 138,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 139,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 140,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 141,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "New Moon",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 142,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 16,
    "DayOfWeek": "Wednesday",
    "Season": "Low Summer",
    "Luna": "New Moon",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 143,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "New Moon Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 144,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "New Moon Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 145,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 146,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 147,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 148,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "First Quarter",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 149,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 23,
    "DayOfWeek": "Thursday",
    "Season": "Low Summer",
    "Luna": "First Quarter",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 150,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 151,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 152,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 153,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 154,
    "MonthNumber": 7,
    "Month": "Flocktime",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 155,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "Full Moon",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 156,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 2,
    "DayOfWeek": "Monday",
    "Season": "Low Summer",
    "Luna": "Full Moon",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 157,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "Full Moon Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 158,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "Full Moon Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 159,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 160,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 161,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waning Gibbous Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 162,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "Last Quarter",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 163,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 9,
    "DayOfWeek": "Tuesday",
    "Season": "Low Summer",
    "Luna": "Last Quarter",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 164,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 165,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 166,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 167,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 168,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waning Crescent Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 169,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "New Moon",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 170,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 16,
    "DayOfWeek": "Wednesday",
    "Season": "Low Summer",
    "Luna": "New Moon",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 171,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "New Moon Fading",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 172,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "New Moon Fading",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 173,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 174,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 175,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 176,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Low Summer",
    "Luna": "First Quarter",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 177,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 23,
    "DayOfWeek": "Thursday",
    "Season": "Low Summer",
    "Luna": "First Quarter",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 178,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Low Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 179,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Low Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 180,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 181,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 182,
    "MonthNumber": 8,
    "Month": "Wealsun",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Low Summer",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 183,
    "MonthNumber": 9,
    "Month": "Richfest",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Mid Summer",
    "Luna": "Full Moon",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 184,
    "MonthNumber": 9,
    "Month": "Richfest",
    "Day": 2,
    "DayOfWeek": "Monday",
    "Season": "Mid Summer",
    "Luna": "Full Moon",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 185,
    "MonthNumber": 9,
    "Month": "Richfest",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Mid Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 186,
    "MonthNumber": 9,
    "Month": "Richfest",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Mid Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Full Moon Fading",
    "Solstace": "The Summer Solstace is the longest day of the year.",
    "Special": ""
  },
  {
    "RecordNumber": 187,
    "MonthNumber": 9,
    "Month": "Richfest",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Mid Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 188,
    "MonthNumber": 9,
    "Month": "Richfest",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Mid Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 189,
    "MonthNumber": 9,
    "Month": "Richfest",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Mid Summer",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 190,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "Last Quarter",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 191,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 2,
    "DayOfWeek": "Tuesday",
    "Season": "High Summer",
    "Luna": "Last Quarter",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 192,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 193,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 194,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waning Crescent",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 195,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waning Crescent",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 196,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waning Crescent Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 197,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "New Moon",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 198,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 9,
    "DayOfWeek": "Wednesday",
    "Season": "High Summer",
    "Luna": "New Moon",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 199,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "New Moon Fading",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 200,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "New Moon Fading",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 201,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 202,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 203,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 204,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "First Quarter",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 205,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 16,
    "DayOfWeek": "Thursday",
    "Season": "High Summer",
    "Luna": "First Quarter",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 206,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 207,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 208,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 209,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 210,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 211,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "Full Moon",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 212,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 23,
    "DayOfWeek": "Tuesday",
    "Season": "High Summer",
    "Luna": "Full Moon",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 213,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 214,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 215,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 216,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 217,
    "MonthNumber": 10,
    "Month": "Reaping",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 218,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "Last Quarter",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 219,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 2,
    "DayOfWeek": "Tuesday",
    "Season": "High Summer",
    "Luna": "Last Quarter",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 220,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 221,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 222,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waning Crescent",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 223,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waning Crescent",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 224,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waning Crescent Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 225,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "New Moon",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 226,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 9,
    "DayOfWeek": "Wednesday",
    "Season": "High Summer",
    "Luna": "New Moon",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 227,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "New Moon Fading",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 228,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "New Moon Fading",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 229,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 230,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 231,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 232,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "First Quarter",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 233,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 16,
    "DayOfWeek": "Thursday",
    "Season": "High Summer",
    "Luna": "First Quarter",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 234,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "First Quarter Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 235,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "First Quarter Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 236,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 237,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 238,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 239,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "Full Moon",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 240,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 23,
    "DayOfWeek": "Tuesday",
    "Season": "High Summer",
    "Luna": "Full Moon",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 241,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 242,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 243,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 244,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 245,
    "MonthNumber": 11,
    "Month": "Goodmonth",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 246,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "Last Quarter",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 247,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 2,
    "DayOfWeek": "Tuesday",
    "Season": "High Summer",
    "Luna": "Last Quarter",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 248,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 249,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "Last Quarter Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 250,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waning Crescent",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 251,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waning Crescent",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 252,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waning Crescent Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 253,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "New Moon",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 254,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 9,
    "DayOfWeek": "Wednesday",
    "Season": "High Summer",
    "Luna": "New Moon",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 255,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "New Moon Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 256,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "New Moon Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 257,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 258,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 259,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waxing Crescent Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 260,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "First Quarter",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 261,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 16,
    "DayOfWeek": "Thursday",
    "Season": "High Summer",
    "Luna": "First Quarter",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 262,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 263,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "First Quarter Fading",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 264,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 265,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 266,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 267,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "High Summer",
    "Luna": "Full Moon",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 268,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 23,
    "DayOfWeek": "Tuesday",
    "Season": "High Summer",
    "Luna": "Full Moon",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 269,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "High Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 270,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "High Summer",
    "Luna": "Full Moon Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 271,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 272,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 273,
    "MonthNumber": 12,
    "Month": "Harvester",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "High Summer",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 274,
    "MonthNumber": 13,
    "Month": "Brewfest",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "This seven-day period marks the transition from Summer to Autumn.",
    "Luna": "Last Quarter",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 275,
    "MonthNumber": 13,
    "Month": "Brewfest",
    "Day": 2,
    "DayOfWeek": "Monday",
    "Season": "This seven-day period marks the transition from Summer to Autumn.",
    "Luna": "Last Quarter",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 276,
    "MonthNumber": 13,
    "Month": "Brewfest",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "This seven-day period marks the transition from Summer to Autumn.",
    "Luna": "Last Quarter Fading",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 277,
    "MonthNumber": 13,
    "Month": "Brewfest",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "This seven-day period marks the transition from Summer to Autumn.",
    "Luna": "Last Quarter Fading",
    "Celene": "Full Moon Fading",
    "Solstace": "The Autumn Equinox, also known as the Autumnal Equinox, is when the night and day are approximately equal in length, marking the beginning of Spring and the approach of Summer.",
    "Special": ""
  },
  {
    "RecordNumber": 278,
    "MonthNumber": 13,
    "Month": "Brewfest",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "This seven-day period marks the transition from Summer to Autumn.",
    "Luna": "Waning Crescent",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 279,
    "MonthNumber": 13,
    "Month": "Brewfest",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "This seven-day period marks the transition from Summer to Autumn.",
    "Luna": "Waning Crescent",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 280,
    "MonthNumber": 13,
    "Month": "Brewfest",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "This seven-day period marks the transition from Summer to Autumn.",
    "Luna": "Waning Crescent Fading",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 281,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Autumn",
    "Luna": "New Moon",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 282,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 2,
    "DayOfWeek": "Tuesday",
    "Season": "Autumn",
    "Luna": "New Moon",
    "Celene": "Full Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 283,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Autumn",
    "Luna": "New Moon Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 284,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Autumn",
    "Luna": "New Moon Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 285,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Autumn",
    "Luna": "Waxing Crescent",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 286,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Autumn",
    "Luna": "Waxing Crescent",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 287,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Autumn",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Waning Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 288,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Autumn",
    "Luna": "First Quarter",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 289,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 9,
    "DayOfWeek": "Wednesday",
    "Season": "Autumn",
    "Luna": "First Quarter",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 290,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Autumn",
    "Luna": "First Quarter Fading",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 291,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Autumn",
    "Luna": "First Quarter Fading",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 292,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Autumn",
    "Luna": "Waxing Gibbous",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 293,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Autumn",
    "Luna": "Waxing Gibbous",
    "Celene": "Waning Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 294,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Autumn",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 295,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Autumn",
    "Luna": "Full Moon",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 296,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 16,
    "DayOfWeek": "Thursday",
    "Season": "Autumn",
    "Luna": "Full Moon",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 297,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Autumn",
    "Luna": "Full Moon Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 298,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Autumn",
    "Luna": "Full Moon Fading",
    "Celene": "Last Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 299,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Autumn",
    "Luna": "Waning Gibbous",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 300,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Autumn",
    "Luna": "Waning Gibbous",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 301,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Autumn",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 302,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Autumn",
    "Luna": "Last Quarter",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 303,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 23,
    "DayOfWeek": "Tuesday",
    "Season": "Autumn",
    "Luna": "Last Quarter",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 304,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Autumn",
    "Luna": "Last Quarter Fading",
    "Celene": "Last Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 305,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Autumn",
    "Luna": "Last Quarter Fading",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 306,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Autumn",
    "Luna": "Waning Crescent",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 307,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Autumn",
    "Luna": "Waning Crescent",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 308,
    "MonthNumber": 14,
    "Month": "Patchwell",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Autumn",
    "Luna": "Waning Crescent Fading",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 309,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Autumn",
    "Luna": "New Moon",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 310,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 2,
    "DayOfWeek": "Tuesday",
    "Season": "Autumn",
    "Luna": "New Moon",
    "Celene": "Waning Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 311,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Autumn",
    "Luna": "New Moon Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 312,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Autumn",
    "Luna": "New Moon Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 313,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Autumn",
    "Luna": "Waxing Crescent",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 314,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Autumn",
    "Luna": "Waxing Crescent",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 315,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Autumn",
    "Luna": "Waxing Crescent Fading",
    "Celene": "Waning Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 316,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Autumn",
    "Luna": "First Quarter",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 317,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 9,
    "DayOfWeek": "Wednesday",
    "Season": "Autumn",
    "Luna": "First Quarter",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 318,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Autumn",
    "Luna": "First Quarter Fading",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 319,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Autumn",
    "Luna": "First Quarter Fading",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 320,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Autumn",
    "Luna": "Waxing Gibbous",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 321,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Autumn",
    "Luna": "Waxing Gibbous",
    "Celene": "New Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 322,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Autumn",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 323,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Autumn",
    "Luna": "Full Moon",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 324,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 16,
    "DayOfWeek": "Thursday",
    "Season": "Autumn",
    "Luna": "Full Moon",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 325,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Autumn",
    "Luna": "Full Moon Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 326,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Autumn",
    "Luna": "Full Moon Fading",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 327,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Autumn",
    "Luna": "Waning Gibbous",
    "Celene": "New Moon Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 328,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Autumn",
    "Luna": "Waning Gibbous",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 329,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Autumn",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 330,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Autumn",
    "Luna": "Last Quarter",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 331,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 23,
    "DayOfWeek": "Tuesday",
    "Season": "Autumn",
    "Luna": "Last Quarter",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 332,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Autumn",
    "Luna": "Last Quarter Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 333,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Autumn",
    "Luna": "Last Quarter Fading",
    "Celene": "Waxing Crescent",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 334,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Autumn",
    "Luna": "Waning Crescent",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 335,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Autumn",
    "Luna": "Waning Crescent",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 336,
    "MonthNumber": 15,
    "Month": "Ready'reat",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Autumn",
    "Luna": "Waning Crescent Fading",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 337,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 1,
    "DayOfWeek": "Starday",
    "Season": "Winter",
    "Luna": "New Moon",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 338,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 2,
    "DayOfWeek": "Tuesday",
    "Season": "Winter",
    "Luna": "New Moon",
    "Celene": "Waxing Crescent Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 339,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 3,
    "DayOfWeek": "Moonday",
    "Season": "Winter",
    "Luna": "New Moon Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 340,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 4,
    "DayOfWeek": "Godsday",
    "Season": "Winter",
    "Luna": "New Moon Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 341,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 5,
    "DayOfWeek": "Waterday",
    "Season": "Winter",
    "Luna": "Waxing Crescent",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 342,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 6,
    "DayOfWeek": "Earthday",
    "Season": "Winter",
    "Luna": "Waxing Crescent",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 343,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 7,
    "DayOfWeek": "Freeday",
    "Season": "Winter",
    "Luna": "Waxing Crescent Fading",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 344,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 8,
    "DayOfWeek": "Starday",
    "Season": "Winter",
    "Luna": "First Quarter",
    "Celene": "First Quarter",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 345,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 9,
    "DayOfWeek": "Wednesday",
    "Season": "Winter",
    "Luna": "First Quarter",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 346,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 10,
    "DayOfWeek": "Moonday",
    "Season": "Winter",
    "Luna": "First Quarter Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 347,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 11,
    "DayOfWeek": "Godsday",
    "Season": "Winter",
    "Luna": "First Quarter Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 348,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 12,
    "DayOfWeek": "Waterday",
    "Season": "Winter",
    "Luna": "Waxing Gibbous",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 349,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 13,
    "DayOfWeek": "Earthday",
    "Season": "Winter",
    "Luna": "Waxing Gibbous",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 350,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 14,
    "DayOfWeek": "Freeday",
    "Season": "Winter",
    "Luna": "Waxing Gibbous Fading",
    "Celene": "First Quarter Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 351,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 15,
    "DayOfWeek": "Starday",
    "Season": "Winter",
    "Luna": "Full Moon",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 352,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 16,
    "DayOfWeek": "Thursday",
    "Season": "Winter",
    "Luna": "Full Moon",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 353,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 17,
    "DayOfWeek": "Moonday",
    "Season": "Winter",
    "Luna": "Full Moon Fading",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 354,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 18,
    "DayOfWeek": "Godsday",
    "Season": "Winter",
    "Luna": "Full Moon Fading",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 355,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 19,
    "DayOfWeek": "Waterday",
    "Season": "Winter",
    "Luna": "Waning Gibbous",
    "Celene": "Waxing Gibbous",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 356,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 20,
    "DayOfWeek": "Earthday",
    "Season": "Winter",
    "Luna": "Waning Gibbous",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 357,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 21,
    "DayOfWeek": "Freeday",
    "Season": "Winter",
    "Luna": "Waning Gibbous Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 358,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 22,
    "DayOfWeek": "Starday",
    "Season": "Winter",
    "Luna": "Last Quarter",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 359,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 23,
    "DayOfWeek": "Tuesday",
    "Season": "Winter",
    "Luna": "Last Quarter",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 360,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 24,
    "DayOfWeek": "Moonday",
    "Season": "Winter",
    "Luna": "Last Quarter Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 361,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 25,
    "DayOfWeek": "Godsday",
    "Season": "Winter",
    "Luna": "Last Quarter Fading",
    "Celene": "Waxing Gibbous Fading",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 362,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 26,
    "DayOfWeek": "Waterday",
    "Season": "Winter",
    "Luna": "Waning Crescent",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 363,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 27,
    "DayOfWeek": "Earthday",
    "Season": "Winter",
    "Luna": "Waning Crescent",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  },
  {
    "RecordNumber": 364,
    "MonthNumber": 16,
    "Month": "Sunsebb",
    "Day": 28,
    "DayOfWeek": "Freeday",
    "Season": "Winter",
    "Luna": "Waning Crescent Fading",
    "Celene": "Full Moon",
    "Solstace": "",
    "Special": ""
  }
)